server:
  port: 8081

  management:
    endpoints:
      web:
        exposure:
          include: '*'
    endpoint:
      health:
        show-details: always

spring:
  boot:
    admin:
      client:
        url: http://localhost:8085
  banner:
    location=banner.txt:
  datasource:
    username: postgres
    password: root
    url: jdbc:postgresql://localhost:5432/matchingservice
    driver-class-name: org.postgresql.Driver
    initialization-mode: always
    separator: ;;
  jpa:
    #    show-sql: true
    database: postgresql
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL9Dialect
        jdbc.lob.non_contextual_creation: true
        format_sql: true
logging:
  file:
    name: matching-app.log


# Aggregator service paths
aggregator:
  base-path: http://localhost:8082
  offers-path: /offers
  products-path: /allProducts

# TroubleTicket service paths
troubleticket:
  base-path: http://localhost:8083
  tickets-path: /tickets
